name: Build Android

on:
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install app dependencies
        run: npm install

      - name: Build app
        run: npm run build:prod

      - name: Install Capacitor
        run: cd resources/mobile && npm install

      - name: Capacitor update
        run: cd resources/mobile && npx cap update

      - name: Capacitor copy
        run: cd resources/mobile && npx cap copy

      - name: Build app bundle
        run: cd resources/mobile/android && gradle bundle

      - name: Extract Android signing key from env
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" | base64 -di > resources/mobile/android/release.decrypted.jks

      - name: Sign dev build
        run: jarsigner -keystore resources/mobile/android/release.decrypted.jks -storepass "${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" -signedjar ./resources/mobile/android/app/build/outputs/bundle/release/app-release-signed.aab ./resources/mobile/android/app/build/outputs/bundle/release/app-release.aab key0

      - name: Upload release bundle
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: resources/mobile/android/app/build/outputs/bundle/release/app-release-signed.aab
          retention-days: 60
